.github/workflows/testing.js.yml
cypress/integration/copying.spec.js
package.json

I tested the following:
* Na toevoegen argumenten werkt de default test nog - ng serve gebruiken en geen andere versies uitchecken.
* Mergen naar mhdirkse/master. Check dat je handmatig kunt gaan triggeren.
* Vul een willekeurige backend versie in - check in de output dat die wordt uitgechecked.
* Vul een willekeurige tag in van de front-end - check dat die wordt uitgechecked.
* Vul in dat webjars gebruikt moeten worden - check dat dat gebeurt

Test webjar and fix flakyness

---

angular.json

Update angular.json so components are not set to standalone by default on creation

Create non-standalone components by default

---

package.json

Ik maak deze PR voor het maken van de webjar. Dit om het risico op conflicten zo klein mogelijk te houden.

Set version to 0.0.55 for the next development cycle

---

angular.json

Angular version 17 encourages standalone components: [docs](https://angular.io/guide/standalone-components).

Set standalone components to true in angular.json

---

cypress/e2e/copying.cy.js
cypress/e2e/testtab_edit.cy.js
cypress/support/commands.ts

The if-statement in the deleteAllTestReports would always give a length of 1 and it was called asynchronously. Because it was asynchronous it caused a race condition somehow, making the test flacky.
Applied resetApp method where applicable now that the deleteAllTestReports works (which is called in the resetApp method)

Fix for the deleteAllTestReports command for Cypress tests

---

cypress/e2e/debug_download.cy.js
cypress/e2e/testtab.cy.js
cypress/e2e/testtab_withOneReport.cy.js
package.json

Removed references to ibissource and changed them to wearefrank so any url is correct with the new organization.
Closes: #377.

Change all references to ibissource organization to wearefrank

---

src/app/report/edit-display/edit-display.component.ts
src/app/shared/services/http.service.ts
src/app/test/test.component.ts

Merge should be done with PR [249](https://github.com/wearefrank/ladybug/pull/249) of the ladybug project.
rerunReport in Debug tab is now disabled until after PR for this branch is done.

Changed the rerun report so that it now works with updated API

---

cypress/e2e/debug_show-warnings-and-errors.cy.ts
src/app/debug/debug.component.ts
src/app/shared/components/toast/toast.component.html
src/app/shared/services/http.service.ts
src/app/shared/services/toast.service.ts

Like the old ladybug, errors and warnings that occur for the storage of a view are now shown in the frontend.
After conferring with @jacodg we decided a toast with a preview of the error was the best solution.
Closes: #379.
@wearefrank/frontend-reviewers 
Old:
New:

Feature: errors and warnings are now shown in a toast for a view storage

---

src/app/compare/compare-tree/compare-tree.component.ts
src/app/debug/table/table.component.ts
src/app/shared/services/helper.service.ts
src/app/shared/services/http.service.ts
src/app/test/test.component.ts

There were two functions (one in table.components, one in test.components) that had a string concat within an array.reduce call and after I changed the concat to a template, linter complained that array.reduce wasn't allowed and therefor i changed the code there.

changed all the string concats in ladybug-frontend to string template

---

src/app/debug/debug-tree/debug-tree.component.ts
src/app/shared/enums/checkpoint-type.ts
src/app/shared/interfaces/checkpoint.ts
src/app/shared/pipes/checkpoint-type.pipe.ts

Because the value for the type of checkpoint is sent as an integer starting at 1, I didn't see a way to use const string types as enums, that's why this solution goes againt our frontend conventions. I'm open to any suggestions
Closes #467.

fix: debug tree indentation for end point checkpoints

---

.eslintrc.json
src/app/debug/debug-tree/debug-tree.component.ts
src/app/debug/debug.component.html
src/app/debug/debug.component.ts
src/app/debug/filter-side-drawer/filter-side-drawer.component.html
src/app/debug/filter-side-drawer/filter-side-drawer.component.spec.ts
src/app/debug/filter-side-drawer/filter-side-drawer.component.ts
src/app/debug/table/table.component.html
src/app/debug/table/table.component.spec.ts
src/app/debug/table/table.component.ts
src/app/shared/interfaces/table-settings.ts
src/app/shared/interfaces/view.ts
src/app/shared/services/http.service.ts
src/app/test/test.component.ts

One step of many to change the way components talk to each other and using types everywhere.
The state of the debug component is now passed to its children, updating when one of its children emits an event.
This means that data is now passed from parent to child instead of child1 to parent to child2.
Also did a small code cleanup.
Please only review what's been changed in this PR, a lot still needs to be refactored, which will be done in steps.

Refactor implement types

---

src/app/debug/debug-tree/debug-tree.component.ts
src/app/shared/classes/report-hierarchy-transformer.ts

Created a class for transforming report to hierarchy structure for reusability.
Also added the getImage method here so the new class doesnt depend on the helper service.
The helper service still has the getImage method which will be removed when the jqx-tree is removed from the compare tab.

Refactor: create class for transforming report to hierarchy structure

---

package.json
pnpm-lock.yaml
src/app/debug/debug-tree/debug-tree.component.html
src/app/debug/debug-tree/debug-tree.component.ts

Clicking a report that's already openen in the debug-tree will now select it, instead of opening again.
If multiple reports are opened, clicking a node doesnt also select other nodes with the same name anymore.
Closes #37.
Closes #478.

Fix: open same report

---

src/app/debug/table/table.component.html
src/app/debug/table/table.component.ts

When trying to open multiple reports while the setting for opening multiple reports is disabled it no longer opens any reports.
Closes #486.

fix: opening multiple reports at once with setting disabled

---

src/app/debug/table/table.component.html

closes #554 
A small fix so the headers stay visible on screen while scrolling down the table.

Table component sticky header

---

src/app/shared/interfaces/test-list-item.ts
src/app/test/test.component.html
src/app/test/test.component.ts

Closes #429 
Error message is now shown in the test table instead of a toast, so it is clear which error correlates for the specific report.

Fix: Report run error specification

---

src/app/app.component.ts

When closing a tab like the compare tab, it goes back to the previous tab.
Closes #589.

fix: remember last page when closing a tab

---

src/app/debug/debug-tree/debug-tree.component.ts

Closes #637.
After conferring with @jacodg, we decided that this solution made sense the most.
Checkpoints hidden by black box view in the debug tree, stay hidden after updating the report.

fix: hidden checkpoints stay hidden in blackbox view after report update

---

cypress/e2e/debug/labels.cy.ts
cypress/e2e/debug/refresh.cy.ts
cypress/e2e/debug/reportGenerator.cy.ts
cypress/e2e/debug/runningReports.cy.ts
cypress/e2e/debug/toast.cy.ts
cypress/e2e/debug/transformation.cy.ts
cypress/e2e/test/testtab.cy.ts
cypress/e2e/transformation.cy.ts

Removed unnecessary cy.wait calls to make cypress tests faster

Refactor: Remove unnecessary cy.wait calls

---

cypress/e2e/test/testtab.cy.ts
src/app/shared/interfaces/test-list-item.ts
src/app/test/test-folder-tree/test-folder-tree.component.html
src/app/test/test-folder-tree/test-folder-tree.component.ts
src/app/test/test-table/test-table.component.html
src/app/test/test-table/test-table.component.ts
src/app/test/test.component.html
src/app/test/test.component.ts

Previously folders in the test tab did not update correctly and also just didn't work correctly.
Folder tree will now update as soon as a report is moved.
Folders are now also sorted alphabetically.
Closes #595 
Closes #320

fix: folder tree in test tab

---

src/app/shared/components/metadata-table/metadata-table.component.html

Previously metadata table did not show the name of the checkpoint, only the name of the report.

refactor: show checkpoint name in the metadata table component

---

src/app/compare/compare.component.ts

Third scrollbar is now removed.
Before:
After:
Closes #572

refactor: remove third scrollbar from diff editor

---

src/app/shared/classes/report-hierarchy-transformer.ts
src/app/shared/enums/checkpoint-type.ts

Indentation and icons for thread checkpoints are now correct in the tree
Closes #673 
Previously:
Now:

fix: indentation and icons for thread checkpoints

---

cypress/e2e/debug/aboutOpenedReports.cy.ts
package.json
pnpm-lock.yaml
src/app/compare/compare-tree/compare-tree.component.ts
src/app/debug/debug-tree/debug-tree.component.ts
src/app/test/test-folder-tree/test-folder-tree.component.ts

Hierarchy lines have been added to tree view on all tabs to show node indentation 
before:
after:

feat: added hierarchy lines to show node indentation in tree view

---

src/app/debug/table/table.component.ts
src/app/report/edit-display/edit-display.component.css
src/app/report/edit-display/edit-display.component.html
src/app/report/edit-display/edit-display.component.ts
src/app/shared/classes/report-hierarchy-transformer.ts
src/app/shared/components/toast/toast.component.html
src/app/shared/interfaces/checkpoint.ts
src/app/shared/interfaces/report.ts
src/app/shared/interfaces/toast.ts
src/app/shared/services/toast.service.ts
src/app/shared/util/report-util.ts

Previously reports in the debug tab could be edited in a readonly storage even if the backend did not allow it.
Now when trying to edit a report in the debug tab that is in a read only storage a toast is shown that allows the user to copy to the test tab instead:
After copying the report to the test tab, a new toast appears showing the copy was successfull with a button to go to the test tab:
Closes #745

Fix: readonly storage

---

src/app/report/edit-display/edit-display.component.ts

Trying to rerun a report with storage id 0 would give a toast error because in javascript 0 is a falsy value.

fix: rerun report with storage id 0

---

src/app/shared/components/toast/toast.component.html
src/app/shared/components/toast/toast.component.spec.ts
src/app/shared/components/toast/toast.component.ts

Click to show detailed description for error toast messages now works again.
Also added a unit test to make sure this functionality keeps working in the future.
Closes #715

Fix: detailed toast

---

src/app/debug/table/table.component.html

Previously, trying to delete a report from a non crud storage, an error would occur:
Now, the delete button is not visible if the current view is not a crud storage:

fix: hide delete button if current view does not have a crudstorage

---

src/app/report/edit-display/edit-display.component.css
src/app/test/test.component.css
src/app/test/test.component.html
src/styles.css

Previously buttons in the test tab were all in one row without a clear distinction on what the scope of their action entails:
Now the buttons are separated by their scope which makes them much more intuitive:
Closes #753

Feat: buttons in testtab are separated by the scope of their action

---

cypress/e2e/no-profile/debug/deleteReports.cy.ts
cypress/support/commands.ts

This PR intends to let the Cypress tests of ladybug-frontend succeed. First, the test is relaxed so that it does not fail because of issue https://github.com/wearefrank/ladybug-frontend/issues/699. When the name of a report is not like `/Simple report` but like `nullSimple report`, it will succeed with this PR. Next, the database storage is not cleared through the UI but through the test webapp. This works as a workaround for https://github.com/wearefrank/ladybug-frontend/issues/785 but it is also useful after that issue will have been fixed. The command to clear the database storage is meant for beforeEach() functions, not to test the UI.

Do not test issue 699 and clear database storage throgh test webapp

---

src/app/test/test-folder-tree/test-folder-tree.component.ts
src/app/test/test.component.ts

Backend returns null values inside string, causing errors in if conditions.
This is a temporary frontend fix. This should be fixed in the backend.

Fix: reports in test tab have null prefixed to path

---

src/app/debug/filter-side-drawer/filter-side-drawer.component.ts
src/app/debug/filter-side-drawer/filter.service.ts
src/app/shared/components/toast/toast.component.css
src/app/shared/components/toast/toast.component.html
src/app/shared/components/toast/toast.component.ts

Previously toast messages could be hidden if the filter side panel was opened, like described in #858.
Any toasts are now automatically offset when the filter panel is opened:

Fix: toast messages are no longer hidden behind filter side panel

---

cypress/e2e/no-profile/1-first.spec.ts
cypress/e2e/no-profile/test/compare.cy.ts
cypress/e2e/no-profile/test/testtab.cy.ts
cypress/e2e/storage-xml/1-pre-existing-report.spec.ts
cypress/support/commands.ts
src/app/test/test-settings-modal/test-settings-modal.component.html
src/app/test/test-table/test-table.component.html
src/app/test/test-table/test-table.component.ts
src/app/test/test.component.html
src/app/test/test.component.ts

Test tab now has a compare button, located in the `Selected` button section:
Compare button is only visible if exactly 2 reports are selected, just like in the debug tab.
Also added the necessary cypress tests.
Added additional cypress test for the `show storage ids` setting in test tab
Closes #782

Compare in test tab

---

cypress/e2e/no-profile/keep_state.cy.ts
cypress/e2e/no-profile/test/testtab.cy.ts
cypress/support/commands.ts
src/app/test/test-table/test-table.component.html
src/app/test/test.component.ts

Previously all reports copied to the testtab would automatically be checked.
This has been disabled as it caused all report checkboxes to be reset after a rerun, see #838.
Select all checkbox is also no longer checked if there are no reports in the table.
Closes #838

Fix: auto select reports in testtab

---

src/app/debug/debug-tab.service.ts
src/app/debug/debug-tree/debug-tree.component.ts
src/app/debug/table/table-settings-modal/table-settings-modal.component.ts
src/app/debug/table/table.component.ts
src/app/shared/components/toast/toast.component.html
src/app/shared/components/toast/toast.component.ts

Previously when changing the transformation in the settings modal a toast would always appear saying you should reopen any open reports to see it with the new transformation.
Now this toast only appears if any reports are opened in the debug tab, and it now has a button to reopen the report directly.
Closes #713

Feat: when changing the transformation in the settings reopen any reports directly from the toast

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/debug/table/table.component.html
src/app/debug/table/table.component.ts
src/app/shared/directives/copy-tooltip.directive.spec.ts
src/app/shared/interfaces/tab.ts

When selecting reports in the debug table, the order is saved, so that when two reports are compared, the first selected report is always on the left side and the last selected report is always on the right side.

Feat: order of selecting reports is saved
