.github/workflows/build.js.yml
.github/workflows/testing.js.yml
package.json

Cypress still needs to be done

Fix the Github Actions

---

src/app/report/report.component.html
src/app/report/report.component.ts
src/app/shared/services/loader.service.ts
src/app/test/test.component.ts

- Each time you would open the report it would increase in tree size

Fix bug when selecting report in tree

---

src/app/shared/components/modals/table-settings-modal/table-settings-modal.component.html

Add extra information on buttons in table settings

---

src/app/debug/debug-tree/debug-tree.component.html
src/app/debug/debug-tree/debug-tree.component.ts

Convert term & possible matches to lower case so it's case-insensitive
Fixes #311

made debug tree search find case-insensitive matches

---

cypress/integration/copying.spec.js
cypress/integration/testtab.spec.js
cypress/integration/testtab_edit.spec.js
cypress/integration/testtab_withOneReport.spec.js
src/app/app.module.ts
src/app/debug/debug-tree/debug-tree.component.ts
src/app/debug/table/table-settings-modal/table-settings-modal.component.html
src/app/debug/table/table.component.html
src/app/report/edit-display/edit-display.component.html
src/app/report/edit-display/edit-display.component.ts
src/app/report/report.component.ts
src/app/shared/interfaces/test-result.ts
src/app/test/delete-modal/delete-modal.component.html
src/app/test/delete-modal/delete-modal.component.spec.ts
src/app/test/delete-modal/delete-modal.component.ts
src/app/test/test-folder-tree/test-folder-tree.component.ts
src/app/test/test.component.html
src/app/test/test.component.ts

- #295
- #299 
- #302 
- #303 
- #304  
- #308 
- #309 
- #313

Additional fixes to the GUI

---

package.json
src/app/app.module.ts
src/app/compare/compare-tree/compare-tree.component.ts
src/app/debug/table/table-settings-modal/table-settings-modal.component.ts
src/app/debug/table/table.component.ts
src/app/shared/services/helper.service.ts
src/app/shared/services/http.service.ts
src/app/test/test-settings-modal/test-settings-modal.component.ts
src/app/test/test.component.ts
yarn.lock

Peer dependencies conflicts have been resolved.
Ngx cookie service has been removed and replaced with localstorage.

Build(deps) peer dependencies

---

src/app/debug/table/table.component.html

Remove padding, problem from merging

chore: fix styling

---

angular.json
package.json

Update angular json file so that ng build includes LICENSE, README.md and package.json in dist folder

Update build options

---

package.json

Deze PR voorkomt dat iemand hetzelfde versienummer gebruikt voor een andere release.

Set version to 0.0.54 for the next development cycle

---

cypress/e2e/debug_custom-editor.cy.ts
cypress/support/commands.ts
src/app/custom-editor/custom-editor.component.html
src/app/custom-editor/custom-editor.component.ts

Created extra view in editor component to allow pretty printing json files.
Also created cypress tests to test existing views, Xml and Raw.
[255](https://github.com/wearefrank/ladybug/issues/225) Created issue on ladybug backend repository to have an option to create a report with a json file, as this is not testable with cypress right now.

Pretty print for json files

---

cypress/support/commands.ts

Removed hardcoded link for clearTestReport command

Fixed the issue that would appear when master branch would run test

---

src/app/debug/table/table.component.css
src/app/debug/table/table.component.html

Solves #366
Moved style in app-button class to its own css class.
Replaced app-button in table component with normal buttons while keeping the original content.

Changed app-buttons to normal buttons in table component

---

src/app/app.component.html

This was removed in an earlier PR

fix: show ladybug version in html

---

.eslintrc.json
package.json
src/app/app.component.html
src/app/compare/compare-tree/compare-tree.component.html
src/app/custom-editor/custom-editor.component.html
src/app/debug/active-filters/active-filters.component.html
src/app/debug/debug-tree/debug-tree.component.html
src/app/debug/debug.component.html
src/app/debug/filter-side-drawer/filter-side-drawer.component.html
src/app/debug/table/table-settings-modal/table-settings-modal.component.html
src/app/debug/table/table.component.html
src/app/report/edit-display/edit-display.component.html
src/app/report/report.component.html
src/app/shared/components/button/button.component.html
src/app/shared/components/toast/toast.component.html
src/app/test/test.component.html
yarn.lock

Add linter rules for no-interpolation-in-attributes and attributes-order. More rules will be added in later PR's

Add linter rules for sorting angular html attributes

---

src/app/app.component.ts

Version is now retrieved from package.json in the assets folder, this will be added to the assets folder in the build step. Meaning version is not shown in development.

fix: get version from package.json

---

src/app/app.component.ts

Displaying version is fixed
Closes #449.

fix: fix displaying version

---

src/app/debug/debug-tree/debug-tree.component.css
src/app/debug/debug-tree/debug-tree.component.html

Fix debug tree styling so scrolling works normally, also the button bar is now sticky and doesn't jitter when scrolling.
Closes #484

Fix: debug tree does not fit

---

src/app/shared/classes/report-hierarchy-transformer.ts

Small fix for the debug-tree nesting for abortpoints

Fix: abortpoint nesting

---

src/app/report/report.component.css

removed extra scroll bar from debug tab

fix: remove extra scrollbar

---

cypress/e2e/debug/table.cy.ts
src/app/debug/debug-tree/debug-tree.component.ts
src/app/debug/table/table.component.ts

Fix for table sorting reset on refresh

---

src/app/test/test.component.ts

Test table was not being updated when uploading report. This one line fixes that.

Small fix to update test reports table when uploading a report

---

src/app/compare/compare.component.ts
src/app/report/edit-display/edit-display.component.ts
src/app/shared/interfaces/report.ts
src/app/shared/interfaces/view.ts
tsconfig.json

This allows filtering the views in the compare tab so we only shows views that actually change something in the compare tab.

refactor: filter views in compare tab based on checkpoint matchers

---

src/app/shared/components/toast/toast.component.css
src/app/shared/components/toast/toast.component.html

* Shorten the duration of the success toast messages
* Move the toast messages from the bottom left to the bottom right

Toast message ui improvement

---

cypress/e2e/debug/clickingInTableOpensReport.cy.ts
src/app/app.component.html
src/app/custom-editor/custom-editor.component.css
src/app/custom-editor/custom-editor.component.html
src/app/custom-editor/custom-editor.component.ts
src/app/report/edit-display/edit-display.component.html
src/app/report/edit-display/edit-display.component.ts
src/app/report/report.component.css
src/app/report/report.component.html
src/app/report/report.component.ts
src/styles.css

Statusbar in custom editor component is now always visible.
Scrollbar in tree view is now fitted to height, so top and bottom are visible.
Closes #692

refactor: fix height for debug tab bottom component

---

src/app/debug/table/table.component.html
src/app/debug/table/table.component.ts
src/app/shared/components/loading-spinner/loading-spinner.component.css
src/app/shared/components/loading-spinner/loading-spinner.component.html
src/app/shared/components/loading-spinner/loading-spinner.component.spec.ts
src/app/shared/components/loading-spinner/loading-spinner.component.ts
src/app/test/test.component.html
src/app/test/test.component.ts

Added a loading spinner to streamline cypress testing

Feat: loading progress spinner

---

src/app/app.component.css
src/app/app.component.html
src/app/app.component.ts

Ladybug mascot is now visible again in the application, not just as favicon.

Feat: add ladybug mascot to top right corner next to version

---

package.json
pom.xml

This reverts commit eb7ad554c138161780a1a0a566c9b7148eca3eaa.

Revert "Downgrade corepack"

---

src/app/test/test-table/test-table.component.html

Avoid creating nbsp in the report name html in test tab

---

src/app/debug/filter-side-drawer/filter-side-drawer.component.ts
src/app/debug/table/table.component.ts
src/app/report/edit-form/edit-form.component.ts

This PR is created to fix the issues that were introduced by this commit
https://github.com/wearefrank/ladybug-frontend/commit/1d295f9a35cb90289cbaabb1aeddbf63e97ab8b4
see github actions: https://github.com/wearefrank/ladybug-frontend/actions/runs/13664236232/job/38202055889

Fix errors

---

src/app/debug/table/table.component.html
src/app/debug/table/table.component.spec.ts
src/app/debug/table/table.component.ts

Adds a button to the download dropdown menu to export selected or filtered metadata rows to a csv file.

Export csv
